### ISSUE TITLE
Information dialogue Widget

### ISSUE THREAD

**Issue by diegoasua** [portugueslab/sashimi#87]
Right now information is sparsed across the GUI. It will be nice to have a little `Qlabel` box in the bottom putting all together that shows information such as:
- Current voxel size
- ROI dimensions
- Framerate and a warning if it is lagging behind
- A message when a volume is dropped
- Whether planes overlap or not.

Different kinds of information types should be separated by a vertical slash and a colour code will inform whether things are good or bad

**Comment by vilim** [comment]
Good point! The common convention for this is a statusbar (see around [here](https://github.com/portugueslab/stytra/blob/06d22a3682e8e57f62c8bdc50a2a0a4ca03d5215/stytra/gui/container_windows.py#L106) for the Stytra thing, which features persistent and disappearing messages. Here I think it should be simpler, because it's known beforehand what needs to be show, so just a normal statusbar with labels.

**Comment by vilim** [comment]
The saving status and progress bar can also go into the status bar

**Comment by diegoasua** [comment]
This was implemented in one of the last PRs, closing
