### ISSUE TITLE
Travis usage optimization

### ISSUE THREAD

**Issue by diegoasua** [portugueslab/sashimi#97]
Travis is checking for both the PR and the branch. Why are we checking both? Making Travis run things twice through the same is suboptimal. Also, is it possible to set Travis not to run checks on draft PRs? As they are not ready to merge, no checks are necessary. @vigji

**Comment by vigji** [comment]
I should have change it on Travis settings so that only the PR is built (we don't use branches that are not for PRs atm).
It is possible that this automatically fix also the draft thing, reading from [here](https://travis-ci.community/t/draft-pull-requests-not-being-built/2434/5), but we'll see how things behave. Let's keep this open

**Comment by diegoasua** [comment]
Further to this. Starting with #98 Travis won't check draft PRs anymore and I think now it also only checks the PR but not the branch itself. So this should be resolved. I am therefore closing this issue
